name: .NET Blazor Build and Publish Artifact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_VERSION: "8.0"
      APP_NAME: "BlazorApp1"
      BUILD_CONFIGURATION: "Release"
      DOTNET_PATH: "publish"

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # 3️⃣ Restore
      - name: Restore dependencies
        run: dotnet restore ${{ env.APP_NAME }}

      - name: Dot Net Build
        run: dotnet build --configuration Release

      # 4️⃣ Build
      - name: Publish
        run: dotnet publish --configuration Release --output publish

      # 6️⃣ Upload artifact (FIXED)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-app-artifact
          path: ${{ env.DOTNET_PATH }}
